//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for amlEmail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amlEmail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amlAuthId" type="{}authId"/>
 *         &lt;element name="amlEmailId" type="{}emailId"/>
 *         &lt;element name="amlEmailPassword" type="{}emailPassword"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amlEmail", namespace = "aml", propOrder = {
    "amlAuthId",
    "amlEmailId",
    "amlEmailPassword"
})
public class AmlEmail {

    @XmlElement(required = true)
    protected AuthId amlAuthId;
    @XmlElement(required = true)
    protected EmailId amlEmailId;
    @XmlElement(required = true)
    protected EmailPassword amlEmailPassword;

    /**
     * Gets the value of the amlAuthId property.
     * 
     * @return
     *     possible object is
     *     {@link AuthId }
     *     
     */
    public AuthId getAmlAuthId() {
        return amlAuthId;
    }

    /**
     * Sets the value of the amlAuthId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthId }
     *     
     */
    public void setAmlAuthId(AuthId value) {
        this.amlAuthId = value;
    }

    /**
     * Gets the value of the amlEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link EmailId }
     *     
     */
    public EmailId getAmlEmailId() {
        return amlEmailId;
    }

    /**
     * Sets the value of the amlEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailId }
     *     
     */
    public void setAmlEmailId(EmailId value) {
        this.amlEmailId = value;
    }

    /**
     * Gets the value of the amlEmailPassword property.
     * 
     * @return
     *     possible object is
     *     {@link EmailPassword }
     *     
     */
    public EmailPassword getAmlEmailPassword() {
        return amlEmailPassword;
    }

    /**
     * Sets the value of the amlEmailPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailPassword }
     *     
     */
    public void setAmlEmailPassword(EmailPassword value) {
        this.amlEmailPassword = value;
    }

}
