//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for email complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="email">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="smtpHost" type="{}smtpHost"/>
 *         &lt;element name="smtpPort" type="{}smtpPort"/>
 *         &lt;element name="imapProtocol" type="{}imapProtocol"/>
 *         &lt;element name="imapHost" type="{}imapHost"/>
 *         &lt;element name="imapPort" type="{}imapPort"/>
 *         &lt;element name="amlEmail" type="{aml}amlEmail"/>
 *         &lt;element name="etlEmail" type="{etl}etlEmail"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "email", propOrder = {

})
public class Email {

    @XmlElement(required = true)
    protected SmtpHost smtpHost;
    @XmlElement(required = true)
    protected SmtpPort smtpPort;
    @XmlElement(required = true)
    protected ImapProtocol imapProtocol;
    @XmlElement(required = true)
    protected ImapHost imapHost;
    @XmlElement(required = true)
    protected ImapPort imapPort;
    @XmlElement(required = true)
    protected AmlEmail amlEmail;
    @XmlElement(required = true)
    protected EtlEmail etlEmail;

    /**
     * Gets the value of the smtpHost property.
     * 
     * @return
     *     possible object is
     *     {@link SmtpHost }
     *     
     */
    public SmtpHost getSmtpHost() {
        return smtpHost;
    }

    /**
     * Sets the value of the smtpHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmtpHost }
     *     
     */
    public void setSmtpHost(SmtpHost value) {
        this.smtpHost = value;
    }

    /**
     * Gets the value of the smtpPort property.
     * 
     * @return
     *     possible object is
     *     {@link SmtpPort }
     *     
     */
    public SmtpPort getSmtpPort() {
        return smtpPort;
    }

    /**
     * Sets the value of the smtpPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmtpPort }
     *     
     */
    public void setSmtpPort(SmtpPort value) {
        this.smtpPort = value;
    }

    /**
     * Gets the value of the imapProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link ImapProtocol }
     *     
     */
    public ImapProtocol getImapProtocol() {
        return imapProtocol;
    }

    /**
     * Sets the value of the imapProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImapProtocol }
     *     
     */
    public void setImapProtocol(ImapProtocol value) {
        this.imapProtocol = value;
    }

    /**
     * Gets the value of the imapHost property.
     * 
     * @return
     *     possible object is
     *     {@link ImapHost }
     *     
     */
    public ImapHost getImapHost() {
        return imapHost;
    }

    /**
     * Sets the value of the imapHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImapHost }
     *     
     */
    public void setImapHost(ImapHost value) {
        this.imapHost = value;
    }

    /**
     * Gets the value of the imapPort property.
     * 
     * @return
     *     possible object is
     *     {@link ImapPort }
     *     
     */
    public ImapPort getImapPort() {
        return imapPort;
    }

    /**
     * Sets the value of the imapPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImapPort }
     *     
     */
    public void setImapPort(ImapPort value) {
        this.imapPort = value;
    }

    /**
     * Gets the value of the amlEmail property.
     * 
     * @return
     *     possible object is
     *     {@link AmlEmail }
     *     
     */
    public AmlEmail getAmlEmail() {
        return amlEmail;
    }

    /**
     * Sets the value of the amlEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmlEmail }
     *     
     */
    public void setAmlEmail(AmlEmail value) {
        this.amlEmail = value;
    }

    /**
     * Gets the value of the etlEmail property.
     * 
     * @return
     *     possible object is
     *     {@link EtlEmail }
     *     
     */
    public EtlEmail getEtlEmail() {
        return etlEmail;
    }

    /**
     * Sets the value of the etlEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link EtlEmail }
     *     
     */
    public void setEtlEmail(EtlEmail value) {
        this.etlEmail = value;
    }

}
