//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for etlEmail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="etlEmail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="etlAuthId" type="{}authId"/>
 *         &lt;element name="etlEmailId" type="{}emailId"/>
 *         &lt;element name="etlEmailPassword" type="{}emailPassword"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "etlEmail", namespace = "etl", propOrder = {

})
public class EtlEmail {

    @XmlElement(required = true)
    protected AuthId etlAuthId;
    @XmlElement(required = true)
    protected EmailId etlEmailId;
    @XmlElement(required = true)
    protected EmailPassword etlEmailPassword;

    /**
     * Gets the value of the etlAuthId property.
     * 
     * @return
     *     possible object is
     *     {@link AuthId }
     *     
     */
    public AuthId getEtlAuthId() {
        return etlAuthId;
    }

    /**
     * Sets the value of the etlAuthId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthId }
     *     
     */
    public void setEtlAuthId(AuthId value) {
        this.etlAuthId = value;
    }

    /**
     * Gets the value of the etlEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link EmailId }
     *     
     */
    public EmailId getEtlEmailId() {
        return etlEmailId;
    }

    /**
     * Sets the value of the etlEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailId }
     *     
     */
    public void setEtlEmailId(EmailId value) {
        this.etlEmailId = value;
    }

    /**
     * Gets the value of the etlEmailPassword property.
     * 
     * @return
     *     possible object is
     *     {@link EmailPassword }
     *     
     */
    public EmailPassword getEtlEmailPassword() {
        return etlEmailPassword;
    }

    /**
     * Sets the value of the etlEmailPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailPassword }
     *     
     */
    public void setEtlEmailPassword(EmailPassword value) {
        this.etlEmailPassword = value;
    }

}
