//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ldapDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ldapDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="domain" type="{}domain"/>
 *         &lt;element name="baseDN" type="{}baseDN"/>
 *         &lt;element name="ldapHostIP" type="{}ldapHostIP"/>
 *         &lt;element name="ldapHostPort" type="{}ldapHostPort"/>
 *         &lt;element name="manager" type="{}manager" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ldapDetails", propOrder = {

})
public class LdapDetails {

    @XmlElement(required = true)
    protected Domain domain;
    @XmlElement(required = true)
    protected BaseDN baseDN;
    @XmlElement(required = true)
    protected LdapHostIP ldapHostIP;
    @XmlElement(required = true)
    protected LdapHostPort ldapHostPort;
    protected Manager manager;

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link Domain }
     *     
     */
    public Domain getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Domain }
     *     
     */
    public void setDomain(Domain value) {
        this.domain = value;
    }

    /**
     * Gets the value of the baseDN property.
     * 
     * @return
     *     possible object is
     *     {@link BaseDN }
     *     
     */
    public BaseDN getBaseDN() {
        return baseDN;
    }

    /**
     * Sets the value of the baseDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseDN }
     *     
     */
    public void setBaseDN(BaseDN value) {
        this.baseDN = value;
    }

    /**
     * Gets the value of the ldapHostIP property.
     * 
     * @return
     *     possible object is
     *     {@link LdapHostIP }
     *     
     */
    public LdapHostIP getLdapHostIP() {
        return ldapHostIP;
    }

    /**
     * Sets the value of the ldapHostIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapHostIP }
     *     
     */
    public void setLdapHostIP(LdapHostIP value) {
        this.ldapHostIP = value;
    }

    /**
     * Gets the value of the ldapHostPort property.
     * 
     * @return
     *     possible object is
     *     {@link LdapHostPort }
     *     
     */
    public LdapHostPort getLdapHostPort() {
        return ldapHostPort;
    }

    /**
     * Sets the value of the ldapHostPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapHostPort }
     *     
     */
    public void setLdapHostPort(LdapHostPort value) {
        this.ldapHostPort = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link Manager }
     *     
     */
    public Manager getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Manager }
     *     
     */
    public void setManager(Manager value) {
        this.manager = value;
    }

}
