//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ldapProvider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ldapProvider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ldapDetails" type="{}ldapDetails"/>
 *       &lt;/sequence>
 *       &lt;attribute name="providerType" use="required" type="{}LdapProviderType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ldapProvider", propOrder = {
    "ldapDetails"
})
public class LdapProvider {

    @XmlElement(required = true)
    protected LdapDetails ldapDetails;
    @XmlAttribute(name = "providerType", required = true)
    protected LdapProviderType providerType;

    /**
     * Gets the value of the ldapDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LdapDetails }
     *     
     */
    public LdapDetails getLdapDetails() {
        return ldapDetails;
    }

    /**
     * Sets the value of the ldapDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapDetails }
     *     
     */
    public void setLdapDetails(LdapDetails value) {
        this.ldapDetails = value;
    }

    /**
     * Gets the value of the providerType property.
     * 
     * @return
     *     possible object is
     *     {@link LdapProviderType }
     *     
     */
    public LdapProviderType getProviderType() {
        return providerType;
    }

    /**
     * Sets the value of the providerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapProviderType }
     *     
     */
    public void setProviderType(LdapProviderType value) {
        this.providerType = value;
    }

}
