//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for manager complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="manager">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ldapUsername" type="{}ldapUsername"/>
 *         &lt;element name="ldapPassword" type="{}ldapPassword"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "manager", propOrder = {
    "ldapUsername",
    "ldapPassword"
})
public class Manager {

    @XmlElement(required = true)
    protected LdapUsername ldapUsername;
    @XmlElement(required = true)
    protected LdapPassword ldapPassword;

    /**
     * Gets the value of the ldapUsername property.
     * 
     * @return
     *     possible object is
     *     {@link LdapUsername }
     *     
     */
    public LdapUsername getLdapUsername() {
        return ldapUsername;
    }

    /**
     * Sets the value of the ldapUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapUsername }
     *     
     */
    public void setLdapUsername(LdapUsername value) {
        this.ldapUsername = value;
    }

    /**
     * Gets the value of the ldapPassword property.
     * 
     * @return
     *     possible object is
     *     {@link LdapPassword }
     *     
     */
    public LdapPassword getLdapPassword() {
        return ldapPassword;
    }

    /**
     * Sets the value of the ldapPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapPassword }
     *     
     */
    public void setLdapPassword(LdapPassword value) {
        this.ldapPassword = value;
    }

}
