//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paths complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paths">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="indexingPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="emailPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paths")
public class Paths {

    @XmlAttribute(name = "indexingPath", required = true)
    protected String indexingPath;
    @XmlAttribute(name = "emailPath", required = true)
    protected String emailPath;

    /**
     * Gets the value of the indexingPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexingPath() {
        return indexingPath;
    }

    /**
     * Sets the value of the indexingPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexingPath(String value) {
        this.indexingPath = value;
    }

    /**
     * Gets the value of the emailPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailPath() {
        return emailPath;
    }

    /**
     * Sets the value of the emailPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailPath(String value) {
        this.emailPath = value;
    }

}
