//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for provider.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="provider">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="database"/>
 *     &lt;enumeration value="ldap"/>
 *     &lt;enumeration value="sso"/>
 *     &lt;enumeration value="webservice"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "provider")
@XmlEnum
public enum Provider {

    @XmlEnumValue("database")
    DATABASE("database"),
    @XmlEnumValue("ldap")
    LDAP("ldap"),
    @XmlEnumValue("sso")
    SSO("sso"),
    @XmlEnumValue("webservice")
    WEBSERVICE("webservice");
    private final String value;

    Provider(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Provider fromValue(String v) {
        for (Provider c: Provider.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
