//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssoDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ssoDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ssoAppId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ssoAppPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ssoURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ssoDetails", propOrder = {
    "ssoAppId",
    "ssoAppPassword",
    "ssoURL"
})
public class SsoDetails {

    @XmlElement(required = true)
    protected String ssoAppId;
    @XmlElement(required = true)
    protected String ssoAppPassword;
    @XmlElement(required = true)
    protected String ssoURL;

    /**
     * Gets the value of the ssoAppId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsoAppId() {
        return ssoAppId;
    }

    /**
     * Sets the value of the ssoAppId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsoAppId(String value) {
        this.ssoAppId = value;
    }

    /**
     * Gets the value of the ssoAppPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsoAppPassword() {
        return ssoAppPassword;
    }

    /**
     * Sets the value of the ssoAppPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsoAppPassword(String value) {
        this.ssoAppPassword = value;
    }

    /**
     * Gets the value of the ssoURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsoURL() {
        return ssoURL;
    }

    /**
     * Sets the value of the ssoURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsoURL(String value) {
        this.ssoURL = value;
    }

}
