//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 05:46:50 PM IST 
//


package com.quantumdataengines.app.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssoProvider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ssoProvider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ssoDetails" type="{}ssoDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ssoProvider", propOrder = {
    "ssoDetails"
})
public class SsoProvider {

    @XmlElement(required = true)
    protected SsoDetails ssoDetails;

    /**
     * Gets the value of the ssoDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SsoDetails }
     *     
     */
    public SsoDetails getSsoDetails() {
        return ssoDetails;
    }

    /**
     * Sets the value of the ssoDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SsoDetails }
     *     
     */
    public void setSsoDetails(SsoDetails value) {
        this.ssoDetails = value;
    }

}
